// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using xmen.Infrastructure.Context;

namespace xmen.infraestructure.Migrations
{
    [DbContext(typeof(CoreContext))]
    [Migration("20220731191503_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("xmen.infraestructure.Entities.Mutant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("And");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CreationDate");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("CreationUser");

                    b.Property<bool>("Deleted")
                        .IsUnicode(false)
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<int>("Humans")
                        .HasColumnType("int")
                        .HasColumnName("Humans");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ModificationDate");

                    b.Property<string>("ModificationUser")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("ModificationUser");

                    b.Property<int>("Mutants")
                        .HasColumnType("int")
                        .HasColumnName("Mutants");

                    b.Property<decimal>("Radio")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Radio");

                    b.HasKey("Id")
                        .HasName("PK_TBL_Mutant");

                    b.ToTable("TBL_Mutant");
                });
#pragma warning restore 612, 618
        }
    }
}
